### ISSUE TITLE
Promise-based API?

### ISSUE THREAD

**Issue by onlywei** [michaelrhodes/simple-sha1#14]
Is there any reason in particular why this library uses a callback-based API and does not even give the option to use a promise-based API for the non-sync version? Especially for the browser version where using the WebCryptoApi already uses promises, why wouldn't the return value be a promise?

**Comment by michaelrhodes** [comment]
Thanks for the question! So I _could_ say that part of the reason is that I don’t want older browsers having to source/load their own Promise polyfills, but honestly I just think Promises are an ugly solution in need of a problem, and thus [eschew them](https://github.com/michaelrhodes/resolve-promise) [constantly](https://github.com/michaelrhodes/subtle-digest).  💁🏻

That said, the API of this module is really tiny, so you should definitely use it as a starting point for your own, Promise-based alternative! 😊
